language: go
go:
  - "1.13"
  - "1.14"
  - "1.15"
  - master
install:
  - make installdeps
cache:
  directories:
    - /home/travis/gopath/pkg/mod
before_script:
  - make generate
script:
  - make test
  - make check-diff
